version: '3.8'
services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - backend
  search-engine-backend:
    depends_on:
      - db
    build: ./search-engine-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - NODE_ENV=$NODE_ENV
      - NODE_LOCAL_PORT=$NODE_LOCAL_PORT
      - MYSQLDB_HOST=db
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_LOCAL_PORT=$MYSQLDB_LOCAL_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend
  search-engine-frontend:
    depends_on:
      - search-engine-backend
    build:
      context: ./search-engine-frontend
      args:
        - ITEMS_API_BASE_URL=$ITEMS_API_BASE_URL
    env_file: ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_LOCAL_PORT
    environment:
      - REACT_LOCAL_PORT:$REACT_LOCAL_PORT
    networks:
      - frontend
volumes:
  db:
networks:
  backend:
  frontend:
